In [63]:
import nltk
import os
import gensim
import pandas as pd
import numpy as np


In [64]:
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to
[nltk_data]    |     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_eng is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]    |

True

In [65]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [66]:
for file in os.listdir('./data'):
    print(file)

story1.txt
story2.txt


In [67]:
corpus= open(r"./data/story1.txt", encoding="unicode_escape").read()
corpus

'Once upon a time, there was a young boy named Arjun who lived in a small town surrounded by hills and rivers. He was very curious about how things worked and always asked questions. His parents often smiled at his curiosity and encouraged him to learn more.\n\nEvery day after school, Arjun would sit with his books and explore different topics. He was especially fascinated by science and technology. He wanted to understand how machines think and whether they could become as intelligent as humans.\n\nOne day, while browsing through an old computer at school, Arjun discovered the concept of artificial intelligence. He read about how machines can learn from data, recognize patterns, and even make decisions. This idea completely amazed him.\n\nHe started imagining a future where machines could help humans solve complex problems. That day, he made a decision that he wanted to become an AI engineer.\n\nArjun began learning programming using free resources. At first, everything seemed difficu

In [68]:
raw_sent = sent_tokenize(corpus)# converts the data to sentences by default basis the full stop. 
raw_sent

['Once upon a time, there was a young boy named Arjun who lived in a small town surrounded by hills and rivers.',
 'He was very curious about how things worked and always asked questions.',
 'His parents often smiled at his curiosity and encouraged him to learn more.',
 'Every day after school, Arjun would sit with his books and explore different topics.',
 'He was especially fascinated by science and technology.',
 'He wanted to understand how machines think and whether they could become as intelligent as humans.',
 'One day, while browsing through an old computer at school, Arjun discovered the concept of artificial intelligence.',
 'He read about how machines can learn from data, recognize patterns, and even make decisions.',
 'This idea completely amazed him.',
 'He started imagining a future where machines could help humans solve complex problems.',
 'That day, he made a decision that he wanted to become an AI engineer.',
 'Arjun began learning programming using free resources.',


In [69]:
for word in raw_sent:
    print(simple_preprocess(word))

['once', 'upon', 'time', 'there', 'was', 'young', 'boy', 'named', 'arjun', 'who', 'lived', 'in', 'small', 'town', 'surrounded', 'by', 'hills', 'and', 'rivers']
['he', 'was', 'very', 'curious', 'about', 'how', 'things', 'worked', 'and', 'always', 'asked', 'questions']
['his', 'parents', 'often', 'smiled', 'at', 'his', 'curiosity', 'and', 'encouraged', 'him', 'to', 'learn', 'more']
['every', 'day', 'after', 'school', 'arjun', 'would', 'sit', 'with', 'his', 'books', 'and', 'explore', 'different', 'topics']
['he', 'was', 'especially', 'fascinated', 'by', 'science', 'and', 'technology']
['he', 'wanted', 'to', 'understand', 'how', 'machines', 'think', 'and', 'whether', 'they', 'could', 'become', 'as', 'intelligent', 'as', 'humans']
['one', 'day', 'while', 'browsing', 'through', 'an', 'old', 'computer', 'at', 'school', 'arjun', 'discovered', 'the', 'concept', 'of', 'artificial', 'intelligence']
['he', 'read', 'about', 'how', 'machines', 'can', 'learn', 'from', 'data', 'recognize', 'patterns',

In [70]:
fodler_path = r"./data"
story =[]
for file in os.listdir(fodler_path):
    if file.endswith(".txt"):
        with open(os.path.join(fodler_path,file), encoding="unicode_escape") as f:
            corpus = f.read()
            raw_sent = sent_tokenize(corpus)
            for sent in raw_sent:
                data = simple_preprocess(sent)
                story.append(data)

In [71]:
story

[['once',
  'upon',
  'time',
  'there',
  'was',
  'young',
  'boy',
  'named',
  'arjun',
  'who',
  'lived',
  'in',
  'small',
  'town',
  'surrounded',
  'by',
  'hills',
  'and',
  'rivers'],
 ['he',
  'was',
  'very',
  'curious',
  'about',
  'how',
  'things',
  'worked',
  'and',
  'always',
  'asked',
  'questions'],
 ['his',
  'parents',
  'often',
  'smiled',
  'at',
  'his',
  'curiosity',
  'and',
  'encouraged',
  'him',
  'to',
  'learn',
  'more'],
 ['every',
  'day',
  'after',
  'school',
  'arjun',
  'would',
  'sit',
  'with',
  'his',
  'books',
  'and',
  'explore',
  'different',
  'topics'],
 ['he',
  'was',
  'especially',
  'fascinated',
  'by',
  'science',
  'and',
  'technology'],
 ['he',
  'wanted',
  'to',
  'understand',
  'how',
  'machines',
  'think',
  'and',
  'whether',
  'they',
  'could',
  'become',
  'as',
  'intelligent',
  'as',
  'humans'],
 ['one',
  'day',
  'while',
  'browsing',
  'through',
  'an',
  'old',
  'computer',
  'at',
  'sc

In [72]:
story[0]

['once',
 'upon',
 'time',
 'there',
 'was',
 'young',
 'boy',
 'named',
 'arjun',
 'who',
 'lived',
 'in',
 'small',
 'town',
 'surrounded',
 'by',
 'hills',
 'and',
 'rivers']

In [73]:
story[-1]

['in',
 'the',
 'end',
 'his',
 'journey',
 'proved',
 'that',
 'with',
 'curiosity',
 'consistency',
 'and',
 'hard',
 'work',
 'anyone',
 'can',
 'achieve',
 'their',
 'dreams',
 'and',
 'create',
 'meaningful',
 'change',
 'in',
 'the',
 'world']

- Word2Vec(......., sg=0) # CBOW
- Word2Vec(......., sg=1) # SKIPGRAM

In [74]:
custom_model= gensim.models.Word2Vec(story, 
                       vector_size=150, # the number of dimensions of the embeddings vector and the default is 100.
                       window=10, 
                       min_count=1 # the words below 5 count will not be used for training the model and will be ignored.
                    )
## BY default this is CBOW as sg=0 in default, if we want to use skip gram then we have to set sg=1.

In [75]:
custom_model.build_vocab(story)

custom_model.corpus_count gives total number of sentences or u may even say len(story)

In [76]:
custom_model.train(story, total_examples=custom_model.corpus_count, epochs=5)

# (104, 2610) #104 is the number of documents and 2610 is the number of unique words.

(1687, 2610)

In [77]:
custom_model.wv['arjun']

array([-1.3979444e-03, -3.7522968e-03,  6.2253424e-03, -6.3357619e-03,
        3.0724595e-03,  3.6618842e-03, -1.0849265e-03,  6.4349528e-03,
        6.3869599e-03, -3.4004399e-03, -3.9009026e-03, -4.5147687e-03,
       -5.5883555e-03, -2.1275727e-03, -4.0133726e-03, -5.8120894e-03,
        6.4912648e-04,  2.0040071e-03,  4.1530952e-03, -1.4865209e-03,
       -3.1912762e-03,  7.5787137e-04,  7.0194859e-04,  5.7251947e-03,
        1.7267860e-04,  4.6122610e-03, -5.8801482e-03,  5.2656862e-03,
       -1.4814573e-03,  5.5141053e-03, -4.9169729e-03,  1.2701224e-03,
        3.1190927e-04, -1.0906832e-04, -3.7177033e-03, -6.0347114e-03,
       -4.2798501e-03, -5.1389071e-03,  1.3944906e-03,  3.8374146e-05,
       -1.0782282e-03,  4.7528786e-03, -2.0204519e-03, -1.1044376e-03,
       -5.7863854e-03, -6.7163790e-03,  6.0569872e-03, -3.9918823e-03,
       -4.1374387e-03,  3.2827752e-03,  4.3695974e-03, -4.7750357e-03,
        6.2095310e-04, -3.8161250e-03,  1.0066190e-03, -2.6904689e-03,
      

In [78]:
len(custom_model.wv['arjun'])

150

In [79]:
custom_model.wv['ai'] ## if there is no word in the vocabulary then it will give key error.

array([ 2.0619647e-03, -4.4619478e-03,  3.2368491e-03,  3.4453284e-03,
        4.3283920e-03,  3.4025940e-03, -4.3299370e-03,  5.6328052e-03,
       -1.2511100e-03, -6.5223873e-03,  5.0545116e-03,  1.6277308e-03,
        4.2127571e-03, -2.2576361e-04,  1.0769820e-03, -2.5985232e-03,
       -4.2252018e-04,  3.0736581e-03, -2.7194670e-03,  5.3726119e-04,
        4.1051134e-03, -3.8814540e-03, -5.0073373e-03,  1.2431665e-03,
       -1.6660057e-03,  2.6459254e-03, -6.3516470e-03,  5.9344317e-03,
       -2.6285814e-03, -1.6260621e-03,  2.3483227e-03,  1.5450423e-03,
       -4.7473400e-03,  3.8349808e-03,  2.1889061e-03,  4.2400165e-03,
        4.9795448e-03, -3.0778907e-03,  6.2681814e-03, -4.2787236e-03,
       -4.8415358e-03, -5.5988370e-03, -2.8406805e-03,  4.6718353e-04,
       -4.8288475e-03,  3.6993765e-03,  5.6751971e-03, -3.8735853e-03,
        2.1531412e-03, -6.2662237e-03, -5.7759034e-03, -3.6186343e-03,
        2.4079150e-03, -1.9049781e-03, -5.0341776e-03,  7.3103438e-04,
      

In [80]:
custom_model.wv['farmers'] ## if there is no word in the vocabulary then it will give key error.

array([ 2.3986390e-03, -4.6580643e-03,  6.1277137e-03, -3.0647123e-03,
       -4.7839042e-03, -1.0131054e-03,  3.1361307e-03,  5.6069001e-04,
        2.6410685e-03,  6.5981541e-03, -2.6487447e-03,  6.0445485e-03,
        4.6218224e-04,  3.6422370e-03,  4.7413390e-03,  1.9929467e-03,
        5.9894691e-03, -6.0003400e-03, -7.8743434e-04,  3.7455596e-03,
        6.1514010e-03,  4.5902696e-03,  3.1414910e-04, -4.2790318e-05,
        5.5288388e-03,  2.4610532e-03,  3.3113714e-03, -4.0966677e-03,
       -2.1294544e-04, -6.1436240e-03, -6.0163974e-04, -5.8152350e-03,
       -9.2681835e-04,  5.9432043e-03, -5.1807808e-03,  5.4935892e-03,
       -4.1755303e-03,  3.9662761e-03,  2.9516311e-03, -4.7371821e-03,
       -5.1069404e-03, -3.6093881e-03, -6.0509960e-03, -3.6512001e-03,
        8.9087198e-04, -5.7290508e-03, -6.5347892e-03,  4.9057081e-03,
        2.6637241e-03, -2.5840751e-03,  2.8181933e-03, -1.3981314e-03,
        6.0882405e-03,  1.9633840e-03,  2.6364652e-03, -6.2063606e-03,
      

In [81]:
custom_model.wv.most_similar("arjun")

[('be', 0.2287348508834839),
 ('slowly', 0.21202515065670013),
 ('whenever', 0.20762531459331512),
 ('lack', 0.2052208036184311),
 ('most', 0.19212833046913147),
 ('on', 0.1743508130311966),
 ('patterns', 0.16559875011444092),
 ('so', 0.1606508493423462),
 ('interest', 0.1602523773908615),
 ('teachers', 0.15139220654964447)]

In [82]:
custom_model.wv.most_similar("ai")

[('lack', 0.24173931777477264),
 ('decided', 0.22202502191066742),
 ('used', 0.21166183054447174),
 ('proper', 0.19160319864749908),
 ('imagining', 0.19146759808063507),
 ('passed', 0.17526577413082123),
 ('slowly', 0.1694324016571045),
 ('understand', 0.1463010609149933),
 ('learned', 0.14380478858947754),
 ('school', 0.14368069171905518)]

In [84]:
custom_model.wv.doesnt_match(["arjun", "engineer","programming", "farmers"])

'arjun'

In [85]:
custom_model.wv.doesnt_match(["weather", "crops","technology", "farmers"])

'weather'

The data we gave for training was very less, hence we are getting poor results. Google used millions of articles based on google news 

In [86]:
custom_model.wv.similarity("ai", "programming")

-0.113292575

In [87]:
custom_model.wv.similarity("arjun", "engineer")

-0.118170865

In [ ]:
### Add more data, train for more epochs and check the accuracy and embedding dimension.